version: '3'
services:
  nest-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/youapp
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY: 321313131312312312dasda323d
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data:
