version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app           # Mount current directory to /app in the container
      - /app/node_modules # Ignore node_modules to avoid conflicts
    ports:
      - "3000:3000"       # Map container port to local machine
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/nest-db # MongoDB connection string
    depends_on:
      - mongo             # Ensure MongoDB starts before the app
    command: npm run start:dev

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
